Routing and blade
RaspAP/raspap-webgui pull request #749
Opened 2021-01-05 08:07 UTC by mp035

**This pull request adds blade templating to all the views, and conventional route support.**  

- The 'templates' folder is left only for historical records, and should be deleted after merging and cursory testing.  It should no longer be referenced in any of the code.  (I can't verify the intended behaviour without deleting the templates folder.)
- All but the most simplistic logic has been transferred from the views into the relevant (controller) file in 'includes'.  **NOTE:** The _includes_ that are actually _controllers_ should probably be moved to an appropriately named folder, but  I didn't want to change your project structure too much because it is already well organized and easy to navigate.
- The 'views' folder should now provide all of the functionality previously in 'templates'
- I have added a section to the installer script to pull in the BladeOne dependency from GitHub, so composer is still not required. 
- I have added a section to the installer script to add a config file to enable lighttpd mod_rewrite during install, and remove it on uninstall.

2021-01-06 07:02 UTC, mp035 commented
Update:  I have removed the 'templates' directory and run a full reinstall on my RPI zero setup, and everything seems to be working as expected after a minor adjustment.

2021-01-06 10:46 UTC, billz commented
@mp035 great Mark. Our CI isn't configured for Laravel's blade templating (yet), so I'm not too concerned about the build errors for now. Will give it a look shortly, thanks.

2021-01-06 13:02 UTC, mp035 commented
Just added some minor fixes, and ran another test of a clean install.  Should be all good to merge when you are happy.

2021-01-27 07:40 UTC, billz commented
@mp035 thanks Mark. Now that v2.6 is released I can devote more time to this. 

Routing works predictably and the Blade templates are functional. One oddity I noticed is the sidebar briefly appears collapsed on every page load. Unclear if this is related to Blade but worth a look.

2021-02-02 12:56 UTC, billz commented
The routing, template logic cleanup + several other fixes is merged with #791 and b21ea0d. The UI issue with the sidebar toggle state persists. For this reason I'll hold off integrating Blade for now.

2021-02-04 04:07 UTC, mp035 commented
Hi Billz,
I've already shipped the device I was testing the code on, and moved to a new project.  The blade implementation shouldn't change client side behavior, so I've probably broken something during the rewrite.  I'll take a look at it as soon as I get some free time.

2021-02-11 05:55 UTC, mp035 commented
Found and fixed the issue that was causing the sidebar to briefly toggle during page load.  Please see commit c4881336effe640b0015b46f861d94ad39f4ac78.

2021-02-11 18:52 UTC, glaszig commented
not wanting to derail the topic but what do you guys think about moving the code to something like laravel lumen?

2021-02-12 08:08 UTC, billz commented
@mp035 you may want to give #803 a look

2021-02-16 01:14 UTC, mp035 commented
Fixed https://github.com/RaspAP/raspap-webgui/issues/803 in commit https://github.com/RaspAP/raspap-webgui/pull/749/commits/0cfdfd367529db93bc83fb2d461434f3a2bf28ac

2021-02-22 10:29 UTC, billz commented on installers/common.sh
> +    awk "{gsub(\"/REPLACE_ME\",\"$HTROOT\")}1" $CONFSRC > /tmp/50-raspap-router.conf
It appears the literal `REPLACE_ME` is a placeholder value, so the match is not made.

2021-02-22 10:30 UTC, billz requested changes
Tested updated installer function but #803 persists. Should be resolved by fixing the substitution.

2021-02-23 07:18 UTC, billz commented
@glaszig re: lumen, IIRC it's geared toward microservices. If it has advantages over blade I'm open to exploring it

2021-03-02 13:35 UTC, mp035 commented on installers/common.sh
> +    awk "{gsub(\"/REPLACE_ME\",\"$HTROOT\")}1" $CONFSRC > /tmp/50-raspap-router.conf
Indeed it is a literal.  That is intentional.  Please see lines 5,6 and 7 of 50-raspap-router.conf from my commit and Make sure you are using it.

2021-03-02 17:06 UTC, billz commented on installers/common.sh
> +    awk "{gsub(\"/REPLACE_ME\",\"$HTROOT\")}1" $CONFSRC > /tmp/50-raspap-router.conf
I see this now, thanks Mark. Unfortunately, this is proving to be a sticky bug. See #813 
Unless you have different findings, I will address this in index.php.

2022-06-08 06:22 UTC, closed without merging